### ISSUE TITLE
Incomplete values for some tags

### ISSUE THREAD

**Issue by humanzz** [HyukjinKwon/spark-xml#11]
I'm trying to read the english wikipedia data dump using spark-xml. My setup is as follows:
- zeppelin 0.5.6 (using built it Spark 1.6.0)
- using spark-xml 3.1.0 on scala 2.10

I'm loading the wikipedia pages as follows
`val items = z.sqlContext.read`
`                        .format("com.databricks.spark.xml")`
`                        .option("rowTag", "page")`
`                        .load("<PATH>/enwiki-latest-pages-articles-sample.xml")`

which succeeds and infers a schema that seems reasonable
`org.apache.spark.sql.DataFrame = [id: bigint, ns: bigint, redirect: struct<#VALUE:string,@title:string>, revision: struct<comment:string,contributor:struct<id:bigint,ip:string,username:string>,format:string,id:bigint,minor:string,model:string,parentid:bigint,sha1:string,text:struct<#VALUE:string,@space:string>,timestamp:string>, title: string]`

If I try to `items.select("revision.text.#VALUE")` it gives me a value that's only a prefix to the whole text available in that page meaning the value is not read fully.

Another thing I tried is to do 
`// changing the rowTag from **page** to **text**`
`val items = z.sqlContext.read`
`                        .format("com.databricks.spark.xml")`
`                        .option("rowTag", "text")`
`                        .load("<PATH>/enwiki-latest-pages-articles-sample.xml")`

and I now get
`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 4, localhost): scala.MatchError: ENDDOCUMENT (of class com.sun.xml.internal.stream.events.EndDocumentEvent)`
`	at com.databricks.spark.xml.parsers.StaxXmlParser$.checkEndElement(StaxXmlParser.scala:94)`
`	at com.databricks.spark.xml.util.InferSchema$.com$databricks$spark$xml$util$InferSchema$$inferObject(InferSchema.scala:218)`
`	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:95)`
`	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:83)`
`	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)`
`...`

which seems to suggest that for some reason it's not able to find the end_tag for text even though it is there.

I'm assuming something is wrong with the XML parsing here but I'm not really sure what's special abt the text tag.

I've attached the input file at https://gist.github.com/humanzz/e2e296fd82dccaa5109c

**Comment by humanzz** [comment]
Apologies @HyukjinKwon, I've opened the issue here by mistake. I've posted the issue at the databricks label but I've been meaning to get in touch with you as I see you are the most active commiter for spark-xml :)

The issue now lives at https://github.com/databricks/spark-xml/issues/81

**Comment by HyukjinKwon** [comment]
It is perfectly fine. Thanks for reporting this.
